# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Load environment parameters
      run: |
        touch parameters.env
        echo "DB_URL=${{ secrets.DB_URL }}" >> parameters.env
        echo "DB_TOKEN=${{ secrets.DB_TOKEN }}" >> parameters.env
        echo "DB_ORG=${{ secrets.DB_ORG }}" >> parameters.env
        echo "DB_BUCKET=${{ secrets.DB_BUCKET }}" >> parameters.env
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Upload file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "."
        target: "~/"
        rm: false
    
    - name : execute shell script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script_stop: true
        script: |
          pkill -f startup.sh
          nohup ./startup.sh &