name: Python Package using Conda

on:
  push:
    branches:
      -feature/lstm

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base

    - name: Activate Conda Environment
      run: |
        echo "CONDA_ENV=base" >> $GITHUB_ENV

    - name: Load environment parameters
      run: |
        touch parameters.env
        echo "DB_URL=${{ secrets.DB_URL }}" >> parameters.env
        echo "DB_TOKEN=${{ secrets.DB_TOKEN }}" >> parameters.env
        echo "DB_ORG=${{ secrets.DB_ORG }}" >> parameters.env
        echo "DB_BUCKET=${{ secrets.DB_BUCKET }}" >> parameters.env
        
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
